export const profilesCategory = {
  positions: [
    { position: "president", title: "President" },
    { position: "vice_president", title: "Vice President" },
    { position: "senator", title: "Senator" },
    { position: "representative", title: "Representative" },
    { position: "governor", title: "Governor" },
    { position: "vice_governor", title: "Vice Governor" },
    { position: "secretary", title: "Secretary" },
    { position: "assistant_secretary", title: "Assistant Secretary" },
    { position: "treasurer", title: "Treasurer" },
    { position: "assistant_treasurer", title: "Assistant Treasurer" },
    { position: "auditor", title: "Auditor" },
    { position: "assistant_auditor", title: "Assistant Auditor" },
    { position: "business_manager", title: "Business Manager" },
    { position: "pro", title: "PRO" },
    { position: "department_board", title: "Department Board" },
    { position: "sergeant_at_arms", title: "Sergeant at Arms" },
    { position: "muse", title: "Muse" },
    { position: "sentinel", title: "Sentinel" },
  ],
};
