export const profilesOrder = {
  upper: ["president", "vice_president", "senator"],
  middle: ["representative"],
  lower: [
    "governor",
    "vice_governor",
    "secretary",
    "assistant_secretary",
    "treasurer",
    "assistant_treasurer",
    "auditor",
    "assistant_auditor",
    "business_manager",
    "pro",
    "department_board",
    "sergeant_at_arms",
    "muse",
    "sentinel",
  ],
  departments: ["cas", "cba", "ccje", "ccs", "cea", "cms", "cot", "cte", "lhs"],
};
